// <auto-generated />
using System;
using GymMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymMvc.Migrations
{
    [DbContext(typeof(GymMvcContext))]
    [Migration("20210208165116_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GymMvc.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("GymMvc.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("GymMvc.Models.Modality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("InstructorId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Modality");
                });

            modelBuilder.Entity("GymMvc.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataFinal");

                    b.Property<DateTime>("DataInicial");

                    b.Property<int?>("MembershipId");

                    b.Property<int?>("ModalityId");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("ModalityId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("GymMvc.Models.Modality", b =>
                {
                    b.HasOne("GymMvc.Models.Instructor", "Instructor")
                        .WithMany("Modalities")
                        .HasForeignKey("InstructorId");
                });

            modelBuilder.Entity("GymMvc.Models.Payment", b =>
                {
                    b.HasOne("GymMvc.Models.Membership", "Membership")
                        .WithMany("Payments")
                        .HasForeignKey("MembershipId");

                    b.HasOne("GymMvc.Models.Modality", "Modality")
                        .WithMany("Payments")
                        .HasForeignKey("ModalityId");
                });
#pragma warning restore 612, 618
        }
    }
}
